set_time_format -unit ns -decimal_places 2
create_clock -name {ActlClk} -period 20.000 -waveform {0 10} [get_ports {ActlClk}]
derive_pll_clocks
set_clock_uncertainty -from [get_clocks {ActlClk}] -to [get_clocks {ActlClk}] -setup 0.1
set_clock_uncertainty -from [get_clocks {ActlClk}] -to [get_clocks {ActlClk}] -hold 0.1
set_clock_uncertainty -from [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] -to [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] -setup 0.1
set_clock_uncertainty -from [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] -to [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] -hold 0.1
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Reset_n}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {CLK}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[0]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[1]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[2]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[3]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[4]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[5]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[6]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[7]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[8]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[9]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[10]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[11]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Address[12]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Bank[0]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Bank[1]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Bank[0]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {Bank[1]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[0]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[1]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[2]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[3]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[4]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[5]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[6]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[7]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[8]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[9]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[10]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[11]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[12]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[13]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[14]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[15]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {CAS}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {CKE}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {CS}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQM[0]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQM[1]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[0]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[1]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[2]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[3]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[4]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[5]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[6]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[7]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[8]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[9]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[10]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[11]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[12]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[13]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[14]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {DQ[15]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {RAS}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {WE}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {SdRamEnd}]