/**********************************************************************************************************************
 * \file Player.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Player.h"
#include "math.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define PI_1                        3.1415f
#define PI_2                        1.5708f
#define PI_4                        0.7853f
#define DEGS_FORMULA1 0.2443f
#define DEGS_FORMULA2 0.0668F
#define PLAYER_COLORSEND_RDY        false
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
PLAYER_TRANSACTION_COLOR_STATE Player_TransmitState = CREATE_MAP;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
static PLAYER_MAIN Player_MainUser =
{
        .x_pos = 0u,
        .y_pos = 0u,
        .x_startPosition = 25u,
        .y_startPosition = 25u,
        .fov = PI_2,
        .angle = 0.0f,
        .distance = 0u
};
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
float32 Player_Atan2(float32 y_axis, float32 x_axis)
{
  float32 arctan_approx = 0.0f;
  float32 result;

    if (x_axis == 0.0f)
    {
      result = (y_axis > 0.0f ) ? PI_2 : ((y_axis < 0.0f) ?  -PI_2 : 0.0f) ;
    }
    else
    {
      float32 z = fabsf(y_axis/x_axis);

      arctan_approx = z * ( PI_4 - ( ( z - 1 ) * ( DEGS_FORMULA1 + DEGS_FORMULA2 * z ) ) );
      if (x_axis > 0.0f)
      {
        result = (y_axis >= 0.0f) ? arctan_approx : -arctan_approx;
      }
      else
      {
        result = (y_axis >= 0.0f) ? (PI_1 - arctan_approx) : (-PI_1 + arctan_approx);
      }
    }

  return result;
}

/* This function evaluates and calculates the wall's starting pixel if the user sees it */
static uint8 Player_CalcPixel(PLAYER_MAIN* mainUser, MAP_OBJ* obj, COLOR_PACKET* packet)
{
  uint8 result = 0;
  float32 angle_to_wall;
  uint16 distance_start;
  float32 relative_angle_start;
  float32 relative_angle_end;
  float32 halfFov = mainUser->fov *0.5f;

  bool startInFov;
  bool endInFov;
  bool insideFov;

  packet->y_end = 100u;
  packet->Color = obj->Color;

  /* Calculate start of wall - user position with looking center angle */
  float dxObjStart = (float)obj->Xaxis - (float)mainUser->x_pos;
  float dyObjStart = (float)obj->Yaxis - (float)mainUser->y_pos;
  angle_to_wall = Player_Atan2(dyObjStart, dxObjStart);
  relative_angle_start = angle_to_wall - mainUser->angle;

  while (relative_angle_start > PI_1) { relative_angle_start -= 2* PI_1; };
  while (relative_angle_start < -PI_1) { relative_angle_start += 2* PI_1; };

  float32 xEnd = obj->Xaxis + cosf(obj->Angle) * obj->Length;
  float32 yEnd = obj->Yaxis + sinf(obj->Angle) * obj->Length;
  float32 dxObjEnd = xEnd - mainUser->x_pos;
  float32 dyObjEnd = yEnd - mainUser->y_pos;
  angle_to_wall =  Player_Atan2(dyObjEnd, dxObjEnd);
  relative_angle_end = angle_to_wall - mainUser->angle;

  while (relative_angle_end > PI_1) { relative_angle_end -= 2* PI_1; };
  while (relative_angle_end < -PI_1) { relative_angle_end += 2* PI_1; };
  startInFov = (relative_angle_start > -halfFov && relative_angle_start < halfFov);
  endInFov   = (relative_angle_end   > -halfFov && relative_angle_end   < halfFov);

  insideFov = (startInFov == false && endInFov == false &&
              ((relative_angle_start < -halfFov && relative_angle_end > halfFov) ||
               (relative_angle_end < -halfFov && relative_angle_start > halfFov)));
  if ( startInFov == true)
  {
    packet->x_start = (uint8)( SCREEN_WIDTH * (relative_angle_start + halfFov) / mainUser->fov );
    /* Calculate the distance */
    packet->distance = (uint8)(dxObjStart*dxObjStart + dyObjStart*dyObjStart);

    if (relative_angle_start > 0.0)
    {
      packet->angleStep = fabsf(relative_angle_start) * (180.0f / PI_1);
      packet->type = 3u;
    }
    else if (relative_angle_start == 0.0 )
    {
      packet->angleStep = 0;
      packet->type = 1u;
    }
    else
    {
      packet->angleStep = fabsf(relative_angle_start) * (180.0f / PI_1);
      packet->type = 2u;
    }
    result = 1u;
  }
  else if (endInFov || insideFov)
  {
    float32 startAngle = mainUser->angle - halfFov;
    float tanfUser = tanf(startAngle);
    float tanfWall =  tanf(obj->Angle);
    packet->x_start = 0;

    float32 x_first =
        (obj->Yaxis - tanfWall * obj->Xaxis + tanfUser * mainUser->x_pos - mainUser->y_pos)
        / (tanfUser - tanfWall);
    float32 y_first = (tanfUser*x_first + mainUser->y_pos - tanfUser*mainUser->x_pos);

    /* Calculate start of wall - user position with looking center angle */
    dxObjStart = x_first - (float)mainUser->x_pos;
    dyObjStart = y_first - (float)mainUser->y_pos;
    float dist2 = (dxObjStart*dxObjStart + dyObjStart*dyObjStart);
    packet->distance = (uint8)dist2;

    if (startAngle > 0.0)
    {
      packet->angleStep = (uint8)(fabsf(startAngle) * (180.0f / PI_1));
      packet->type = 3u;
    }
    else if (startAngle == 0.0 )
    {
      packet->angleStep = 0u;
      packet->type = 1u;
    }
    else
    {
      packet->angleStep = (uint8)(fabsf(startAngle) * (180.0f / PI_1));
      packet->type = 2u;
    }
    result = 2u;
  }

  return result;
}

void Player_Task1ms(void)
{
  switch (Player_TransmitState)
  {
    case CREATE_MAP:
    {
      /* The map creation starts here depends on a cfg file maybe */
      
      break;
    }

    default:
    {

      break;
    }
  }

}
