/**********************************************************************************************************************
 * \file Player.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Player.h"
#include "math.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define PI_1                        3.1415f
#define PI_2                        1.6708f
#define PI_4                        0.7853f
#define DEGS_FORMULA1 0.2443f
#define DEGS_FORMULA2 0.0668F
#define PLAYER_COLORSEND_RDY        false
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
PLAYER_TRANSACTION_COLOR_STATE Player_TransmitState = COLOR_PENDING;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
float32 Player_Atan2(float32 y_axis, float32 x_axis)
{
  float32 arctan_approx = 0.0f;
  float32 result;

    if (x_axis == 0.0f)
    {
      result = (y_axis > 0.0f ) ? PI_2 : ((y_axis < 0.0f) ?  -PI_2 : 0.0f) ;
    }
    else
    {
      float32 z =fabsf(y_axis/x_axis);

      arctan_approx = z * ( PI_4 - ( ( z - 1 ) * ( DEGS_FORMULA1 + DEGS_FORMULA2 * z ) ) );
      if (x_axis > 0.0f)
      {
        result = (y_axis >= 0.0f) ? arctan_approx : -arctan_approx;
      }
      else
      {
        result = (y_axis >= 0.0f) ? (PI_1 - arctan_approx) : (-PI_1 + arctan_approx);
      }
    }

  return result;
}

/* This function evaluates and calculates the wall's starting pixel if the user sees it */
static uint8 Player_CheckObjOnFov(PLAYER_MAIN* mainUser, MAP_OBJ* obj, float32 relative_angle_start, float32 relative_angle_end)
{
  uint8 result = 0;
  float32 angle_to_wall;

  bool startInFov;
  bool endInFov;

  /* Calculate start of wall - user position with looking center angle */
  uint8 dxObjStart = mainUser->x_pos - obj->Xaxis;
  uint8 dyObjStart = mainUser->y_pos - obj->Yaxis;

  angle_to_wall = Player_Atan2((float32)dyObjStart, (float32)dxObjStart);
  relative_angle_start = angle_to_wall - mainUser->angle;

  while (relative_angle_start > PI_1) { relative_angle_start -= 2* PI_1; };
  while (relative_angle_start < PI_1) { relative_angle_start += 2* PI_1; };

  uint8 dxObjEnd = mainUser->x_pos - (uint8)((float32)obj->Xaxis + cosf(obj->Angle) * obj->Distance);
  uint8 dyObjEnd = mainUser->y_pos - (uint8)((float32)obj->Yaxis + sinf(obj->Angle) * obj->Distance);
  angle_to_wall =  Player_Atan2((float32)dyObjEnd, (float32)dxObjEnd);
  relative_angle_end = angle_to_wall - mainUser->angle;

  while (relative_angle_end > PI_1) { relative_angle_end -= 2* PI_1; };
  while (relative_angle_end < PI_1) { relative_angle_end += 2* PI_1; };
  startInFov = (fabsf(relative_angle_start) <  (mainUser->fov / 2));
  endInFov = (fabsf(relative_angle_end) <  (mainUser->fov / 2));
  if ( (startInFov == true)  && ( endInFov == true ))
  {
    result = 3;
  }
  else if (startInFov)
  {
    result = 1;
  }
  else if (endInFov)
  {
    result = 2;
  }

  return result;
}

uint8 Player_CalcStartingPixel(PLAYER_MAIN* mainUser, MAP_OBJ* obj, uint8 pixel_start , uint8 pixel_end )
{
  float32 angle_start = 0.0f;
  float32 angle_end = 0.0f;
  uint8 result = Player_CheckObjOnFov(mainUser, obj, angle_start, angle_end);
  if (result == 1)
  {
    pixel_start = (uint8)( SCREEN_WIDTH * (angle_start + (mainUser->fov / 2.0f)) / mainUser->fov );
  }
  else if (result == 2)
  {
    pixel_end = (uint8)( SCREEN_WIDTH * (angle_end + (mainUser->fov / 2.0f)) / mainUser->fov ) ;
  }
  else if (result == 3)
  {
    pixel_start = (uint8)( SCREEN_WIDTH * (angle_start + (mainUser->fov / 2.0f) ) / mainUser->fov);
    pixel_end = (uint8)( SCREEN_WIDTH * (angle_end + (mainUser->fov / 2.0f)) / mainUser->fov);
  }
  else 
  {
    /* This is when the result is zero */
    if ((angle_start < 0.0f) && (angle_end > 0.0f))
    {
      pixel_start = 0U;
      pixel_end = SCREEN_WIDTH;
      result = 4U;
    }
    else if ( (angle_start > 0.0f) && (angle_end < 0.0f))
    {
      pixel_start = 0U;
      pixel_end = SCREEN_WIDTH;
      result = 5U;
    }
  }
  return result;
}

void Player_Task16ms(void)
{
  switch (Player_TransmitState)
  {
    case COLOR_PENDING:
    {
      /* Here we calculate the colors that the user sees */
      
      break;
    }

    default:
    {

      break;
    }
  }

}
