/**********************************************************************************************************************
 * \file Player.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ASW_PLAYER_PLAYER_H_
#define ASW_PLAYER_PLAYER_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "../Asw/Map/Map.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define SCREEN_WIDTH  100.0F
#define SCREEN_HEIGHT 100.0F
/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
typedef union
{
  uint16 U;
  struct
  {
    uint16 x_pos:8;
    uint16 y_pos:8;
  }b;
}Color_Spi0;

typedef union
{
  uint16 U;
  struct
  {
    uint16 color :8;
    uint16 distance :8;
  }b;
}Color_Spi1;

typedef union
{
  uint16 U;
  struct
  {
    uint16 anglestep : 6;
    uint16 type : 3;
    uint16 ack : 7;
  }b;
}Color_Spi2;

 typedef struct
 {
  uint8 x_pos;
  uint8 y_pos;
  uint8 distance;
  float32 angle;
  float32 tanLeftAngle;
  uint8 x_startPosition;
  uint8 y_startPosition;
  float32 fov;
 }PLAYER_MAIN;

 typedef struct
 {
  Color_Spi0 spi0;
  Color_Spi1 spi1;
  Color_Spi2 spi2;
 }COLOR_PACKET;

 typedef enum
 {
  CREATE_MAP,
  COLOR_PENDING,
  COLOR_WAIT,
  COLOR_SEND
 }PLAYER_TRANSACTION_COLOR_STATE;

 /*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
extern PLAYER_TRANSACTION_COLOR_STATE Player_TransmitState;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

uint8 Player_CalcStartingPixel(PLAYER_MAIN* mainUser, MAP_OBJ* obj, uint8 *pixel_start , uint8 *pixel_end );
float32 Player_Atan2(float32 y_axis, float32 x_axis);

#endif /* ASW_PLAYER_PLAYER_H_ */
