LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;

PACKAGE SdRamTypes IS
    -- 8 bits per color (We hope)
    TYPE DataCols_t IS ARRAY (1 DOWNTO 0) OF STD_LOGIC_VECTOR(15 DOWNTO 0);
    TYPE DataCols_ary IS ARRAY (63 DOWNTO 0) OF DataCols_t; --64 data X 4 256 COLORS
    TYPE Address_t IS ARRAY (0 TO 2) OF STD_LOGIC_VECTOR(8 DOWNTO 0);

    TYPE SDRAM_STATE IS
    (
    POWERON,
    DELAY,
    POWERDOWN,
    IDLE,
    MODE_REGISTER_SET,
    ACTIVE_STATE,
    WRITE_STATE,
    WRITE_STORE,
    BURST_TERMINATE_WRITE,
    READ_STATE,
    READ_STORE,
    BURST_TERMINATE_READ,
    PRECHARGE_ALL,
    AUTO_REFRESH_STARTUP,
    SELF_REFRESH_EXIT,
    NOP_WITH_COUNTER,
    NOP
    );
END SdRamTypes;