/**********************************************************************************************************************
 * \file UserOs.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "UserOs.h"
#include "Compilers.h"
#include "IfxStm.h"
#include "../Bsw/Os/include/FreeRTOS.h"
#include "../Bsw/Os/include/task.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define TASK_1_MS_STACK_SIZE 1024

#define TASK_500_MS_STACK_SIZE 1024

#define TASK_1_MS_PRIORITY 2

#define TASK_500_MS_PRIORITY 1
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
StaticTask_t xTaskBuffer[2];

StackType_t xStack_1ms[TASK_1_MS_STACK_SIZE];

StackType_t xStack_500ms[TASK_500_MS_STACK_SIZE];

volatile GameController_State_t GameController_State = CORE0_INIT;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void vApplicationGetIdleTaskMemory( StaticTask_t **ppxIdleTaskTCBBuffer,
                                    StackType_t **ppxIdleTaskStackBuffer,
                                    uint32_t *pulIdleTaskStackSize )
{
/* If the buffers to be provided to the Idle task are declared inside this
function then they must be declared static - otherwise they will be allocated on
the stack and so not exists after this function exits. */
static StaticTask_t xIdleTaskTCB;
static StackType_t uxIdleTaskStack[ configMINIMAL_STACK_SIZE ];

    /* Pass out a pointer to the StaticTask_t structure in which the Idle task's
    state will be stored. */
    *ppxIdleTaskTCBBuffer = &xIdleTaskTCB;

    /* Pass out the array that will be used as the Idle task's stack. */
    *ppxIdleTaskStackBuffer = &uxIdleTaskStack[0];

    /* Pass out the size of the array pointed to by *ppxIdleTaskStackBuffer.
    Note that, as the array is necessarily of type StackType_t,
    configMINIMAL_STACK_SIZE is specified in words, not bytes. */
    *pulIdleTaskStackSize = configMINIMAL_STACK_SIZE;
}

void vApplicationGetTimerTaskMemory( StaticTask_t **ppxTimerTaskTCBBuffer,
StackType_t **ppxTimerTaskStackBuffer,
configSTACK_DEPTH_TYPE *puxTimerTaskStackSize )
{
/* If the buffers to be provided to the Timer task are declared inside this
function then they must be declared static - otherwise they will be allocated on
the stack and so not exists after this function exits. */
static StaticTask_t xTimerTaskTCB;
static StackType_t uxTimerTaskStack[ configTIMER_TASK_STACK_DEPTH ];

/* Pass out a pointer to the StaticTask_t structure in which the Timer
task's state will be stored. */
*ppxTimerTaskTCBBuffer = &xTimerTaskTCB;

/* Pass out the array that will be used as the Timer task's stack. */
*ppxTimerTaskStackBuffer = uxTimerTaskStack;

/* Pass out the size of the array pointed to by *ppxTimerTaskStackBuffer.
Note that, as the array is necessarily of type StackType_t,
configTIMER_TASK_STACK_DEPTH is specified in words, not bytes. */
*puxTimerTaskStackSize = configTIMER_TASK_STACK_DEPTH;
}

void vApplicationIdleHook( void )
{
  /* Here the user can write in case reached a failure in the os */
}


void OsTasks_setupTimerInterrupt(Ifx_STM *stm)
{
    IfxStm_setCompareControl(stm,
                             IfxStm_Comparator_0,
                             IfxStm_ComparatorOffset_0,
                             IfxStm_ComparatorSize_32Bits,
                             IfxStm_ComparatorInterrupt_ir0);

    IfxStm_clearCompareFlag(stm,
                            IfxStm_Comparator_0);

    {
        volatile Ifx_SRC_SRCR *src;
        src = IfxStm_getSrcPointer(stm, IfxStm_Comparator_0);
        IfxSrc_init(src, (IfxSrc_Tos)IfxSrc_Tos_cpu0, configKERNEL_INTERRUPT_PRIORITY);
        IfxSrc_enable(src);
    }

    {
        uint32 stmCount= IfxStm_getLower(stm);
        IfxStm_updateCompare(&MODULE_STM0,
                             IfxStm_Comparator_0,
                             stmCount + (configSTM_CLOCK_HZ/configTICK_RATE_HZ )* 100 );
        IfxStm_enableComparatorInterrupt(stm, IfxStm_Comparator_0);
    }
}

/**
 * FreeRTOS Kernel Tick interrupt provider
 * FreeRTOS needs kernel Tick through an interrupt occurring at configTICK_RATE_HZ rate.
 * The ISR need to call the function vPortSystemTickHandler.
 */
IFX_INTERRUPT(OsTasks_TickProvider, 0, configKERNEL_INTERRUPT_PRIORITY)
{
  uint32 stmCount= IfxStm_getCompare(&MODULE_STM0, IfxStm_Comparator_0);
  IfxStm_updateCompare(&MODULE_STM0,
                               IfxStm_Comparator_0,
                               stmCount + configSTM_CLOCK_HZ/configTICK_RATE_HZ );
    vPortSystemTickHandler();
}





void vTasksInit(void)
{
  OsTasks_setupTimerInterrupt(&MODULE_STM0);
  /* Here we initialize the tasks there */
  vTaskStartScheduler();
}
