/**********************************************************************************************************************
 * \file Walls.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the
 *company in which ordinary course of business you are acting and (ii) Infineon
 *Technologies AG or its licensees. If and as long as no such terms of use are
 *agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 *obtaining a copy of the software and accompanying documentation covered by
 *this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 *and to permit third-parties to whom the Software is furnished to do so, all
 *subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 *the above license grant, this restriction and the following disclaimer, must
 *be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 *solely in the form of machine-executable object code generated by a source
 *language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 *ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Map.h"


/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define MAP_SECTORS_MAX_NUM 13
#define MAP_WALLS_MAX_NUM 20

static MAP_OBJ* Walls_Sector_0[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_1[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_2[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_3[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_4[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_5[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_6[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_7[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_8[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_9[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_10[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_11[MAP_WALLS_MAX_NUM];
static MAP_OBJ* Walls_Sector_12[MAP_WALLS_MAX_NUM];

static SECTOR_ARRAY Map_Sectors[MAP_SECTORS_MAX_NUM] =
{
    {
        Walls_Sector_0,
        0u
    },
    {
        Walls_Sector_1,
        0u
    },
    {
        Walls_Sector_2,
        0u
    },
    {
        Walls_Sector_3,
        0u
    },
    {
        Walls_Sector_4,
        0u
    },
    {
        Walls_Sector_5,
        0u
    },
    {
        Walls_Sector_6,
        0u
    },
    {
        Walls_Sector_7,
        0u
    },
    {
        Walls_Sector_8,
        0u
    },
    {
        Walls_Sector_9,
        0u
    },
    {
        Walls_Sector_10,
        0u
    },
    {
        Walls_Sector_11,
        0u
    },
    {
        Walls_Sector_12,
        0u
    }
};
static uint8 Map_SectorsNum[MAP_SECTORS_MAX_NUM];
static  MAP_t Map_Main = {
  Map_Sectors,
  Map_SectorsNum
};
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static uint8 Sector_AddObj(struct SECTOR_ARRAY *array, MAP_OBJ *obj)
{
  uint8 result = 1U;
  if (array->length < MAP_MAX_OBJ)
  {
    /* Calculate only on initialization the trigonometric information */
    obj->cosAngle = cosf(obj->Angle);
    obj->sinAngle = sinf(obj->Angle);
    obj->tanAngle = tanf(obj->Angle);
    array->map[array->length] = obj;
    array->length++;
  }
  else
  {
    result = 2U;
  }

  return result;
}


static uint8 Sector_RemoveObj(struct SECTOR_ARRAY *array)
{
  uint8 result = 1U;
  if (array->length >= 1u)
  {
    array->map[array->length - 1] = NULL_PTR;
    array->length--;
  } 
  else 
  {
    result = 2U;
  }
  return result;
}


uint8 Map_Init(MAP_CFG_t* MapCfg)
{
  /* Initialize the WallsBuffer first */
  uint8 result = 1U;
  uint8 SectorNum = 0xFFU;

  Map_Main.add = &Sector_AddObj;
  Map_Main.remove = &Sector_RemoveObj;

  for (uint8 i = 0; i < MapCfg->size; i++)
  {
    SectorNum =  MapCfg->MapPtr[i].SectorNumber;
    if (SectorNum > MAP_SECTORS_MAX_NUM)
    {
      result = 3;
      break;
    }
    result = Map_Main.add(&Map_Main.SectorPtr[SectorNum ], &MapCfg->MapPtr[i]);
    if (result == 2)
    {
      break;
    }
    else
    {
      Map_Main.SectorNum[SectorNum]++;
    }
  }

  return result;
}

MAP_OBJ* Map_ReturnObjPtr(MAP_OBJ* MapArray, uint8 idx)
{
    MAP_OBJ* ObjPtr;
    if (idx < MAP_MAX_OBJ)
    {
        ObjPtr = &MapArray[idx];
    }
    else
    {
        ObjPtr = &MapArray[0u];
    }
    return ObjPtr;
}

MAP_OBJ* Sector_ReturnObjptr(MAP_t *map, uint8 deep, uint8 sectorNum)
{
  MAP_OBJ* ObjPtr;

  if (sectorNum < MAP_SECTORS_MAX_NUM)
  {
    ObjPtr = map->SectorPtr[sectorNum].map[deep];
  }
  else
  {
    ObjPtr = map->SectorPtr[0].map[0];
  }
  return ObjPtr;
}
