/**********************************************************************************************************************
 * \file Walls.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the
 *company in which ordinary course of business you are acting and (ii) Infineon
 *Technologies AG or its licensees. If and as long as no such terms of use are
 *agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 *obtaining a copy of the software and accompanying documentation covered by
 *this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 *and to permit third-parties to whom the Software is furnished to do so, all
 *subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 *the above license grant, this restriction and the following disclaimer, must
 *be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 *solely in the form of machine-executable object code generated by a source
 *language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 *ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Map.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
static MAP_OBJ Map_ObjsBuf[MAP_MAX_OBJ];
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
static uint8 Map_AddObj(struct MAP_QUEUE *queue, MAP_OBJ *obj)
{
  uint8 result = 0U;
  if (queue->length < MAP_MAX_OBJ)
  {
    queue->length++;
    obj->NEXT_OBJ =  NULL_PTR;
    obj->PREV_OBJ = queue->last;
    queue->last->NEXT_OBJ= obj;
    queue->last = obj;
    result = 1U;
  } else 
  {
    result = 2U;
  }

  return result;
}


static uint8 Map_RemoveObj(struct MAP_QUEUE *queue, MAP_OBJ *obj)
{
  uint8 result = 1U;
  if (queue->length >= 1u)
  {
    queue->last = queue->last->PREV_OBJ;
    queue->last->NEXT_OBJ = NULL_PTR;
    queue->length--;
  } 
  else 
  {
    result = 0U;
  }
  return result;
}

bool Map_InitQueue(struct MAP_QUEUE *queue, MAP_OBJ *obj)
{
  bool result = false;
  if (obj != NULL_PTR)
  {
    queue->add = &Map_AddObj;
    queue->remove = &Map_RemoveObj;
    queue->first = obj;
    queue->last = obj;
    queue->length++;
    queue->baseIndex = 0u;
    result = true;
  }
  return result;
}

uint8 Map_Init(void)
{
  /* Initialize the WallsBuffer first */
  uint8 result = 1U;
  for (uint8 i = 0; i < MAP_MAX_OBJ; i++)
  {
    Map_ObjsBuf[i].type = WALL;
   }

  return result;
}

MAP_OBJ* Map_ReturnObjPtr(uint8 idx)
{
    MAP_OBJ* ObjPtr;
    if (idx < MAP_MAX_OBJ)
    {
        ObjPtr = &Map_ObjsBuf[idx];
    }
    else
    {
        ObjPtr = &Map_ObjsBuf[0u];
    }
    return ObjPtr;
}
