/**********************************************************************************************************************
 * \file Walls.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the
 *company in which ordinary course of business you are acting and (ii) Infineon
 *Technologies AG or its licensees. If and as long as no such terms of use are
 *agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 *obtaining a copy of the software and accompanying documentation covered by
 *this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 *and to permit third-parties to whom the Software is furnished to do so, all
 *subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 *the above license grant, this restriction and the following disclaimer, must
 *be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 *solely in the form of machine-executable object code generated by a source
 *language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 *ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ASW_MAP_MAP_H_
#define ASW_MAP_MAP_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "stdbool.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define MAP_MAX_OBJ 256u
#define MAP_SECTOR_TYPE 20

typedef enum
{
  WALL,
  DOOR,
  SECTOR_0,
  SECTOR_1,
  SECTOR_2,
  SECTOR_3,
  SECTOR_4,
  SECTOR_5,
  SECTOR_6,
  SECTOR_7,
  SECTOR_8,
  SECTOR_9,
  SECTOR_10,
  SECTOR_11,
  SECTOR_12,
  SECTOR_13,
  SECTOR_14,
  SECTOR_15,
  SECTOR_16,
  SECTOR_17,
  SECTOR_18,
  SECTOR_19
}MAP_OBJ_TYPE;

typedef struct MAP_OBJ_s
{
  /* For now y = ax + b or something similar I need to map some things I guess */
  uint8 Color;
  uint8 Distance;
  uint8 Xaxis;
  uint8 Yaxis;
  uint8 Length;
  float32 Angle;
  float32 cosAngle;
  float32 sinAngle;
  float32 tanAngle;
  MAP_OBJ_TYPE type;
  uint8 SectorNumber;
  struct MAP_OBJ_s *NEXT_OBJ;
  struct MAP_OBJ_s *PREV_OBJ;
}MAP_OBJ;

typedef MAP_OBJ* MAP_OBJ_PTR;

typedef struct
{
    MAP_OBJ* MapPtr;
  uint32 size;
}MAP_CFG_t;

struct SECTOR_ARRAY;

typedef uint8 (*SECTOR_ADD_FUNC)(struct SECTOR_ARRAY *array, MAP_OBJ *obj);
typedef uint8 (*SECTOR_REMOVE_FUNC)(struct SECTOR_ARRAY *array);

typedef struct SECTOR_ARRAY
{
  MAP_OBJ **map;
  uint8 length;
}SECTOR_ARRAY;

typedef struct
{
  SECTOR_ARRAY* SectorPtr;
  uint8*         SectorNum;
  SECTOR_ADD_FUNC add;
  SECTOR_REMOVE_FUNC remove;
}MAP_t;

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
uint8 Map_Init(MAP_CFG_t* MapCfg);
MAP_OBJ* Map_ReturnObjPtr(MAP_OBJ* MapArray, uint8 idx);
MAP_OBJ* Sector_ReturnObjptr(MAP_t *map, uint8 deep, uint8 sectorNum);

#endif /* ASW_WALLS_WALLS_H_ */
