/**********************************************************************************************************************
 * \file Walls.h
 * \copyright Copyright (C) Infineon Technologies AG 2019
 *
 * Use of this file is subject to the terms of use agreed between (i) you or the
 *company in which ordinary course of business you are acting and (ii) Infineon
 *Technologies AG or its licensees. If and as long as no such terms of use are
 *agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 *obtaining a copy of the software and accompanying documentation covered by
 *this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software,
 *and to permit third-parties to whom the Software is furnished to do so, all
 *subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 *the above license grant, this restriction and the following disclaimer, must
 *be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 *solely in the form of machine-executable object code generated by a source
 *language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 *SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR
 *ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 *ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 *DEALINGS IN THE SOFTWARE.
 *********************************************************************************************************************/

#ifndef ASW_MAP_MAP_H_
#define ASW_MAP_MAP_H_

/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Ifx_Types.h"
#include "stdbool.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

#define MAP_MAX_OBJ 128u

typedef enum
{
  WALL,
  DOOR
}MAP_TYPE;

typedef struct MAP_OBJ_s
{
  /* For now y = ax + b or something similar I need to map some things I guess */
  uint8 Color;
  uint8 Distance;
  uint8 Xaxis;
  uint8 Yaxis;
  uint8 Length;
  float32 Angle;
  uint8 Sector;
  MAP_TYPE type;
  struct MAP_OBJ_s *NEXT_OBJ;
  struct MAP_OBJ_s *PREV_OBJ;
}MAP_OBJ;

struct MAP_QUEUE;

typedef uint8 (*MAP_ADD_FUNC)(struct MAP_QUEUE *queue, MAP_OBJ *obj);
typedef uint8 (*MAP_REMOVE_FUNC)(struct MAP_QUEUE *queue, MAP_OBJ *obj);

typedef struct MAP_QUEUE
{
  MAP_OBJ *first;
  MAP_OBJ *last;
  uint8 baseIndex;
  uint8 length;
  MAP_ADD_FUNC add;
  MAP_REMOVE_FUNC remove;
}MAP_QUEUE;

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Data Structures---------------------------------------------------*/
/*********************************************************************************************************************/
 
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
bool Map_InitQueue(struct MAP_QUEUE *queue, MAP_OBJ *obj);
uint8 Map_Init(void) ;
MAP_OBJ* Map_ReturnObjPtr(uint8 idx);

#endif /* ASW_WALLS_WALLS_H_ */
