/**********************************************************************************************************************
 * \file Map_Cfg.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "Map_Cfg.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* 4 walls forming a box */
static MAP_OBJ mapObjects[4] =
{
    /* Left wall */
    {
        .Color = 40,
        .Distance = 0,
        .Xaxis = 0,
        .Yaxis = 0,
        .Length = 50,
        .Angle = 90.0f,
        .type = WALL,
        .SectorNumber = 0u,
        .NEXT_OBJ = &mapObjects[1],
        .PREV_OBJ = NULL
    },

    /* Top wall */
    {
        .Color = 40,
        .Distance = 0,
        .Xaxis = 0,
        .Yaxis = 50,
        .Length = 50,
        .Angle = 0.0f,
        .type = WALL,
        .SectorNumber = 0u,
        .NEXT_OBJ = &mapObjects[2],
        .PREV_OBJ = &mapObjects[0]
    },

    /* Right wall */
    {
        .Color = 40,
        .Distance = 0,
        .Xaxis = 50,
        .Yaxis = 0,
        .Length = 50,
        .Angle = 90.0f,
        .type = WALL,
        .SectorNumber = 0u,
        .NEXT_OBJ = &mapObjects[3],
        .PREV_OBJ = &mapObjects[1]
    },

    /* Bottom wall */
    {
        .Color = 40,
        .Distance = 0,
        .Xaxis = 0,
        .Yaxis = 0,
        .Length = 50,
        .Angle = 0.0f,
        .type = WALL,
        .SectorNumber = 0u,
        .NEXT_OBJ = NULL,
        .PREV_OBJ = &mapObjects[2]
    }
};

/* Map configuration */
MAP_CFG_t MapCfg =
{
    .MapPtr = mapObjects,
    .size   = 4
};
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
