LIBRARY ieee;
USE ieee.std_logic_1164.ALL;
USE ieee.numeric_std.ALL;
LIBRARY work;
USE work.VgaTypes.ALL;
ENTITY Vga IS
    GENERIC (
        SystemFreq : INTEGER := 40000000;
        VsyncFreq : INTEGER := 60;
        HsyncFreq : INTEGER := 37680);

    PORT (
        Reset : IN STD_LOGIC;
        ColorClk : IN STD_LOGIC;
        HsyncClk : OUT STD_LOGIC := '1';
        VsyncClk : OUT STD_LOGIC := '1';
        R : OUT STD_LOGIC_VECTOR (7 DOWNTO 0) := (OTHERS => '0');
        G : OUT STD_LOGIC_VECTOR (7 DOWNTO 0) := (OTHERS => '0');
        B : OUT STD_LOGIC_VECTOR (7 DOWNTO 0) := (OTHERS => '0');
        LineBuffer : IN LineBuffer_t;
        x_axis : OUT unsigned (9 DOWNTO 0) := (OTHERS => '0');
        y_axis : OUT unsigned (9 DOWNTO 0) := (OTHERS => '0');
        HsyncComplete : OUT STD_LOGIC := '0';
        VsyncComplete : OUT STD_LOGIC := '0';
        LineBufferIndex : IN INTEGER;
        PllLocked : IN STD_LOGIC);

END Vga;

ARCHITECTURE rtl OF Vga IS
    CONSTANT VsyncDuty : INTEGER := 4;
    CONSTANT VsyncBackPort : INTEGER := 27;
    CONSTANT VsyncActive : INTEGER := 626;
    CONSTANT VsyncPeriod : INTEGER := 627;

    CONSTANT HsyncDuty : INTEGER := 128;
    CONSTANT HsyncBackPorch : INTEGER := 215;
    CONSTANT HsyncPixel : INTEGER := 1015;
    CONSTANT HsyncPeriod : INTEGER := 1055;

    SIGNAL HsyncCounter : INTEGER := 0;
    SIGNAL VsyncCounter : INTEGER := 0;
    SIGNAL HsyncClk_reg : STD_LOGIC := '1';
    SIGNAL VsyncClk_reg : STD_LOGIC := '1';

    TYPE Sync_State IS
    (
    IDLE_STATE,
    PULSE_STATE,
    BACK_PORCH_STATE,
    ACTIVE_STATE,
    EXTEND_STATE,
    FRONT_PORCH,
    PREPARE_PULSE
    );

    SIGNAL HsyncState : Sync_State := IDLE_STATE;
    SIGNAL VsyncState : Sync_State := IDLE_STATE;
    SIGNAL x_axis_reg : unsigned (9 DOWNTO 0) := (OTHERS => '0');
    SIGNAL y_axis_reg : unsigned (9 DOWNTO 0) := (OTHERS => '0');
    SIGNAL HsyncComplete_reg : STD_LOGIC := '0';
    SIGNAL LineBufferIndex_reg : INTEGER := 0;

BEGIN
    --Update the actual signals
    HsyncClk <= HsyncClk_reg;
    VsyncClk <= VsyncClk_reg;
    --Hsync pulse process
    PROCESS (ColorClk, Reset, PllLocked) IS
    BEGIN
        IF (Reset = '1') THEN
            HsyncClk_reg <= '1';
            HsyncState <= IDLE_STATE;
        ELSIF rising_edge(ColorClk) AND PllLocked = '1' THEN --Here we should increase the counter
            CASE HsyncState IS
                WHEN IDLE_STATE =>
                    HsyncState <= PULSE_STATE;
                    HsyncCounter <= 0;
                    HsyncClk_reg <= NOT HsyncClk_reg;
                    x_axis_reg <= (OTHERS => '0');
                    HsyncComplete_reg <= '0';
                    VsyncCounter <= 0;

                WHEN PULSE_STATE =>
                    IF (HsyncCounter = HsyncDuty) THEN
                        HsyncState <= BACK_PORCH_STATE;
                        HsyncClk_reg <= NOT HsyncClk_reg;
                        x_axis_reg <= (OTHERS => '0');
                    END IF;
                    HsyncCounter <= HsyncCounter + 1;

                WHEN BACK_PORCH_STATE =>
                    IF (HsyncCounter = HsyncBackPorch) THEN
                        HsyncState <= ACTIVE_STATE;
                    END IF;
                    HsyncCounter <= HsyncCounter + 1;
                WHEN ACTIVE_STATE =>
                    IF (HsyncCounter = HsyncPixel) THEN
                        HsyncState <= FRONT_PORCH;
                        HsyncComplete_reg <= '1';
                    ELSE
                        -- 0x320 = 800
                        IF ((x_axis_reg < X"320") AND (VsyncState <= ACTIVE_STATE)) THEN
                            x_axis_reg <= x_axis_reg + 1;
                        END IF;
                    END IF;
                    HsyncCounter <= HsyncCounter + 1;

                WHEN FRONT_PORCH =>
                    -- Prepare to start the new pulse (We need to check the HsyncComplete inside the VsyncProcess thats why we need an extra state)
                    IF (HsyncCounter = HsyncPeriod) THEN
                        VsyncCounter <= VsyncCounter + 1;
                        HsyncComplete_reg <= '0';
                        HsyncCounter <= 0;
                        HsyncState <= PREPARE_PULSE;
                    ELSE
                        HsyncCounter <= HsyncCounter + 1;
                    END IF;

                WHEN PREPARE_PULSE =>
                    HsyncClk_reg <= NOT HsyncClk_reg;
                    HsyncState <= PULSE_STATE;
                    -- Here we reset the VsyncCounter at the exact time of the pulse that will be generated by Vsync and Hsync
                    IF (VsyncCounter = VsyncPeriod) THEN
                        VsyncCounter <= 0;
                    END IF;

                WHEN OTHERS => NULL;
            END CASE;
        END IF;
    END PROCESS;

    --Vsync pulse process
    PROCESS (ColorClk, Reset, PllLocked) IS
    BEGIN
        IF (Reset = '1') THEN
            VsyncClk_reg <= '1';
            VsyncState <= IDLE_STATE;
            VsyncComplete <= '0';
            LineBufferIndex_reg <= 0;
        ELSIF rising_edge(ColorClk) AND PllLocked = '1' THEN --Here we should increase the counter
            CASE VsyncState IS
                WHEN IDLE_STATE =>
                    VsyncState <= PULSE_STATE;
                    VsyncClk_reg <= NOT VsyncClk_reg;
                    y_axis_reg <= (OTHERS => '0');
                    VsyncComplete <= '0';
                WHEN PULSE_STATE =>
                    IF (VsyncCounter = VsyncDuty) THEN
                        VsyncState <= BACK_PORCH_STATE;
                        VsyncClk_reg <= NOT VsyncClk_reg;
                    END IF;

                WHEN BACK_PORCH_STATE =>
                    IF (VsyncCounter = VsyncBackPort) THEN
                        VsyncState <= ACTIVE_STATE;
                    END IF;

                WHEN ACTIVE_STATE =>
                    IF (VsyncCounter = VsyncActive) THEN
                        VsyncComplete <= '1';
                        VsyncState <= FRONT_PORCH;
                    ELSIF HsyncComplete_reg = '1' THEN
                        y_axis_reg <= y_axis_reg + 1;
                    END IF;

                WHEN FRONT_PORCH =>
                    IF (((VsyncCounter = VsyncPeriod) OR (VsyncCounter = 0)) AND (HsyncState = PREPARE_PULSE)) THEN
                        LineBufferIndex_reg <= LineBufferIndex;
                        y_axis_reg <= (OTHERS => '0');
                        VsyncState <= PULSE_STATE;
                        VsyncClk_reg <= NOT VsyncClk_reg;
                        VsyncComplete <= '0';
                    END IF;

                WHEN OTHERS => NULL;
            END CASE;
        END IF;
    END PROCESS;

    --color pulse process much more complicated
    PROCESS (ColorClk, Reset, PllLocked) IS
    BEGIN
        IF (Reset = '1') THEN
            R <= (OTHERS => '0');
            G <= (OTHERS => '0');
            B <= (OTHERS => '0');
        ELSIF rising_edge(ColorClk) AND PllLocked = '1' THEN --Here we should increase the counter
            IF (HsyncState = ACTIVE_STATE AND VsyncState = ACTIVE_STATE) THEN
                G <= LineBuffer(LineBufferIndex_reg) (to_integer(x_axis_reg)) (23 DOWNTO 16);
                R <= LineBuffer(LineBufferIndex_reg) (to_integer(x_axis_reg)) (15 DOWNTO 8);
                B <= LineBuffer(LineBufferIndex_reg) (to_integer(x_axis_reg)) (7 DOWNTO 0);
            ELSE
                R <= (OTHERS => '0');
                G <= (OTHERS => '0');
                B <= (OTHERS => '0');
            END IF;
        END IF;
    END PROCESS;
    -- assign the out signals
    x_axis <= x_axis_reg;
    y_axis <= y_axis_reg;
    HsyncComplete <= HsyncComplete_reg;
END ARCHITECTURE;