/**********************************************************************************************************************
 * \file TempControl.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include <TempControl.h>
#include "../Bsw/I2c/I2c.h"
#include "../Bsw/Pwm/PWM_GENERATOR.h"
#include "Cpu/Std/IfxCpu_Intrinsics.h"
#include "../Asw/UserOs/UserOs.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define TEMP_KITRONIC_BAUD 100000
#define TEMP_FIT 27
#define TEMP_MAX 32
#define TEMP_MIN 25

#define PWM_FAN_FREQ 250
#define PWM_FAN_PORT &IfxGtm_TOM0_9_TOUT11_P00_2_OUT

#define TEMPCONTROL_LUT_NUM 11U

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* Temp Sensor Related variables */
Temperature_Controller TempControl_TempCmd = 0;
float TempControl_PreviousTemp;
float TempControl_TempVal;
uint8 TempControl_Timer = 0;
Temperature_State TempControl_State = WAIT_CORE0_INIT;
static uint8 TempControl_Adr = 0x48;
static IfxI2c_I2c_Device TempControl_I2cDev;

/* Pwm related variables */
static IfxGtm_Tom_Pwm_Driver TempControl_PwmFanDrv;
static uint16 TempControl_PwmDuty = 20u;

boolean GiveCommand;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/
static const uint16 TempControl_PwmLut[TEMPCONTROL_LUT_NUM] = {
        15u, 25u, 50u, 75u, 100u, 125u, 150u, 175u, 200u, 225u, 249u
};

static const float TempControl_TempLut[TEMPCONTROL_LUT_NUM] = {
        20.0f,
        25.0f,
        30.0f,
        35.0f,
        40.0f,
        45.0f,
        50.0f,
        55.0f,
        60.0f,
        65.0f,
        70.0f
};
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
static void TempControl_EvalPwm(void);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
void TempControl_Init(void)
{
    /* First init the tom pwm for the fan */
    TomPwm_Init(&TempControl_PwmFanDrv ,PWM_FAN_FREQ, TempControl_PwmDuty , IfxGtm_Tom_Ch_ClkSrc_cmuFxclk1 , PWM_FAN_PORT, IfxSrc_Tos_cpu1);
    /* Init the Temperature sensor */
    I2c_Init(&TempControl_I2cDev, &IfxI2c0_SCL_P13_1_INOUT, &IfxI2c0_SDA_P13_2_INOUT, TempControl_Adr, TEMP_KITRONIC_BAUD);
}

void TempControl_ReadTemp(void)
{
  volatile uint8 TempBytes[2];
  uint16 TempSum;

  I2c_ReadBytes(&TempControl_I2cDev,TempBytes,2);

  TempSum = ((TempBytes[0]<<8)|TempBytes[1])>>4;
  TempControl_TempVal = (float) TempSum*0.0625;
}


void TempControl_task(void)
{
    switch (TempControl_State)
    {
        case WAIT_CORE0_INIT:
        {
            __dsync();
            if (GameController_State == CORE1_INIT)
            {
                __ldmst(&GameController_State, 0xFFFF, PROGRAM_STARTED);
                __dsync();
                TempControl_State = START_TEMPCONTROL;
            }
        }
        break;

        case START_TEMPCONTROL:
        {
            TempControl_ReadTemp();
            TempControl_EvalPwm();
            TomPwm_SetDutyCycle(&TempControl_PwmFanDrv, TempControl_PwmDuty);
        }
        break;
    }
}

void TempControl_GetTempVal(float *RoomTemp)
{
  *RoomTemp = TempControl_TempVal;
}

void TempControl_GetTempCommand(Temperature_Controller *tempCommand)
{
  *tempCommand = TempControl_TempCmd;
}

static void TempControl_EvalPwm(void)
{
    boolean tempFound = FALSE;
    uint8 lutLowBoundary = 0;
    float tempActDiff;
    float tempDiff;
    uint16 pwmActDiff;
    uint16 pwmDiff;

    /* Find the lookup table low boundary */
    for (uint8 i = 0; i < TEMPCONTROL_LUT_NUM - 1; i ++)
    {
        if (TempControl_TempLut[i] <=  TempControl_TempVal)
        {
            lutLowBoundary = i;
            tempActDiff = TempControl_TempVal - TempControl_TempLut[i];
            tempDiff = TempControl_TempLut[i + 1] - TempControl_TempLut[i];
            pwmDiff = TempControl_PwmLut[i + 1] - TempControl_PwmLut[i];
            tempFound = TRUE;
            break;
        }
    }

    if (tempFound ==  TRUE)
    {
        /* Compute the next fan value */
        pwmActDiff = (uint16)(pwmDiff * (tempActDiff / tempDiff));

        /* Update the new dutycycle */
        TempControl_PwmDuty = TempControl_PwmLut[lutLowBoundary] + pwmActDiff;
    }
    else if (TempControl_TempVal < TempControl_TempLut[0]) /* Temperature is too small */
    {
        /* Update the new dutycycle */
        TempControl_PwmDuty = TempControl_PwmLut[0];
    }
    else /*Temperature is too big */
    {
        TempControl_PwmDuty = TempControl_PwmLut[TEMPCONTROL_LUT_NUM - 1];
    }
}
