/**********************************************************************************************************************
 * \file PixelSend.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "../Bsw/QuadSpi/QSpiAtom.h"
#include "../Bsw/Ports/Ports.h"
#include "PixelSend.h"

/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define PIXELSEND_READY MODULE_P00,3
#define QSPI_FREQUENCY 10000000
#define PIXELSEND_MAXSIZE 512U
#define PIXELSEND_MOSI1                       0u
#define PIXELSEND_MOSI2                       1u
#define PIXELSEND_MOSI3                       2u
#define PIXELSEND_CHIP_SELECT                 3u
#define PIXELSEND_CLOCK                       4u
#define PIXELSEND_MASTERCLOCK                 &IfxGtm_ATOM0_0_TOUT0_P02_0_OUT
#define PIXELSEND_RESET MODULE_P00,4
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* SPI Configuration Registers */
IfxGtm_Atom_ToutMapP PixelSend_SpiSignals[5] =
{
    [PIXELSEND_MOSI1] = &IfxGtm_ATOM0_1_TOUT47_P22_0_OUT,
    [PIXELSEND_MOSI2] = &IfxGtm_ATOM0_2_TOUT33_P33_11_OUT,
    [PIXELSEND_MOSI3] = &IfxGtm_ATOM0_3_TOUT49_P22_2_OUT,
    [PIXELSEND_CHIP_SELECT] = &IfxGtm_ATOM0_4_TOUT50_P22_3_OUT,
    [PIXELSEND_CLOCK] = &IfxGtm_ATOM0_5_TOUT41_P23_0_OUT
};

static uint16 PixelSend_SpiData1[PIXELSEND_MAXSIZE];
static uint16 PixelSend_SpiData2[PIXELSEND_MAXSIZE];
static uint16 PixelSend_SpiData3[PIXELSEND_MAXSIZE];

QSPIATOM_INPUTBUFFER PixelSend_SpiData[3] =
{
  PixelSend_SpiData1,
  PixelSend_SpiData2,
  PixelSend_SpiData3
};
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
void PixeSend_SetData(void);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/

void PixelSend_Init(void)
{
  boolean SpiReady;
  Ports_SetPinInputNoPull(&PIXELSEND_READY);

  /* Initialize the fpga reset pin */
  Ports_SetPinOutputPullup(&PIXELSEND_RESET);
  /* Initialize the Spi Pin */
  QSpiAtom_Init(QSPI_FREQUENCY,  PIXELSEND_MASTERCLOCK, PixelSend_SpiSignals, PixelSend_SpiData);

  Ifx_TickTime time100ms = IfxStm_getTicksFromMilliseconds(BSP_DEFAULT_TIMER, 100);
  wait(time100ms);
  /* Start the fpga */
  Ports_SetPinOutputFalse(&PIXELSEND_RESET);
  wait(time100ms);
  PixeSend_SetData();

  SpiReady = Ports_GetPinState(&PIXELSEND_READY);
  /* Wait till the port becomes true */
  while (SpiReady == FALSE)
  {
    SpiReady = Ports_GetPinState(&PIXELSEND_READY);
  }
}


void PixeSend_SetData(void)
{
  for (uint8 i = 0 ; i < 100; i++)
  {
    PixelSend_SpiData[0][i] = i+1;
    PixelSend_SpiData[1][i] = i+1;
    PixelSend_SpiData[2][i] = i+1;
  }
}



void PixelSend_SendSpi(uint16 size)
{
  boolean SpiReady;
  /* Wait till the port becomes high */
  SpiReady = Ports_GetPinState(&PIXELSEND_READY);
  if (SpiReady == TRUE)
  {
    QSpiAtom_StartQuadSpiTranscaction(size);
  }
  else
  {
    /* Do nothing */
  }
}
