/**********************************************************************************************************************
 * \file PixelSend.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/
#include "../Bsw/Spi/Spi.h"
#include "../Bsw/Ports/Ports.h"
#include "PixelSend.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define PIXELSEND_READY MODULE_P00,3
/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/*********************************************************************************************************************/
/* SPI Configuration Registers */
SpiMasterPins_t PixelSend_SpiPins = {
    &IfxQspi1_SCLK_P10_2_OUT,
    &IfxQspi1_MTSR_P10_3_OUT,
    &IfxQspi1_MRSTA_P10_1_IN
};

SpiMaster_t PixelSend_SpiMaster;

SpiMasterCfg_t PixelSend_SpiCfg = {
    &PixelSend_SpiMaster,
    10,
    11,
    12
};

SpiChannel_t PixelSend_SpiChannel;

SpiChannelConfig PixelSend_SpiChannelCfg = {
    &IfxQspi1_SLSO5_P11_2_OUT,
    PIXELSEND_SPIBAUDRATE,
    0,
    SpiIf_ShiftClock_shiftTransmitDataOnLeadingEdge,
    SpiIf_DataHeading_msbFirst
};

uint32 PixelSend_SpiTx[300];
uint32 PixelSend_SpiRx[300];
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/

/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(SpimasterTxPixelSend, 0, 10);                  /* SPI Master ISR for transmit data         */
IFX_INTERRUPT(SpimasterRxPixelSend, 0, 11);                  /* SPI Master ISR for receive data          */
IFX_INTERRUPT(SpimasterErPixelSend, 0, 12);                 /* SPI Master ISR for error                 */


 void SpimasterTxPixelSend(void)
 {
     IfxCpu_enableInterrupts();
     IfxQspi_SpiMaster_isrTransmit(PixelSend_SpiCfg.SpiMasterPtr);
 }

 void SpimasterRxPixelSend(void )
 {
     IfxCpu_enableInterrupts();
     IfxQspi_SpiMaster_isrReceive(PixelSend_SpiCfg.SpiMasterPtr);
 }

 void SpimasterErPixelSend(void)
 {
     IfxCpu_enableInterrupts();
     IfxQspi_SpiMaster_isrError(PixelSend_SpiCfg.SpiMasterPtr);
 }


void PixelSend_Init(void)
{
  /* Initialize the Spi Pin */
  Spi_Init(&PixelSend_SpiPins, &PixelSend_SpiCfg);

  Spi_ChannelInit(&PixelSend_SpiCfg, &PixelSend_SpiChannel, &PixelSend_SpiChannelCfg);

  Ports_SetPinInputNoPull(&PIXELSEND_READY);

  /* Wait till the port becomes high */
  while (Ports_GetPinState(&PIXELSEND_READY) == FALSE) {}
}



void PixelSend_SendSpi(uint16 size)
{
  PixelSend_SpiTx[0] = 0x23482428;
  PixelSend_SpiTx[1] = 0xac232df9;
  PixelSend_SpiTx[2] = 0xac232df9;
  PixelSend_SpiTx[3] = 0xac232df9;
  PixelSend_SpiTx[4] = 0xac232df9;
  PixelSend_SpiTx[5] = 0xac232df9;
  PixelSend_SpiTx[6] = 0xac232df9;
  PixelSend_SpiTx[7] = 0xac232df9;

  if (Ports_GetPinState(&PIXELSEND_READY) == FALSE)
  {
    Spi_WriteBytes(&PixelSend_SpiChannel,PixelSend_SpiTx, size);
  }
  else
  {
    /* Here we do nothing */
  }
}
