set_time_format -unit ns -decimal_places 2
create_clock -name {VideoCtrl_ActlClk} -period 20.000 -waveform {0 10} [get_ports {VideoCtrl_ActlClk}]
derive_pll_clocks
derive_clock_uncertainty
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}]  0.1 [get_ports { VideoCtrl_Reset_n}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[0]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[1]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[2]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[3]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[4]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[5]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[6]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[7]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[8]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[9]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[10]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[11]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Address[12]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Bank[0]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_Bank[1]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[0]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[1]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[2]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[3]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[4]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[5]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[6]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[7]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[8]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[9]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[10]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[11]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[12]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[13]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[14]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[15]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_CAS}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_CKE}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports { VideoCtrl_SdRamCS}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQM[0]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQM[1]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[0]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[1]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[2]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[3]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[4]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[5]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[6]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[7]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[8]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[9]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[10]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[11]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[12]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[13]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[14]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DQ[15]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_RAS}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_WE}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DebugLeds[0]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DebugLeds[1]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DebugLeds[2]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DebugLeds[3]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DebugLeds[4]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DebugLeds[5]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DebugLeds[6]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_DebugLeds[7]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[1]}] 0.1 [get_ports {VideoCtrl_SdRamClkOut}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_SpiClk}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_Cs}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_Si[0]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_Si[1]}]
set_input_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_Si[2]}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_So}]
set_output_delay -add_delay -clock [get_clocks {SdRamPll|altpll_component|auto_generated|pll1|clk[0]}] 0.1 [get_ports {VideoCtrl_SpiReady}]

