/**********************************************************************************************************************
 * \file TimerTom.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/*********************************************************************************************************************/
/*-----------------------------------------------------Includes------------------------------------------------------*/
/*********************************************************************************************************************/

#include "../Bsw/QuadSpi/QSpiAtom.h"
#include "../Bsw/Dma/Dma.h"
#include "IfxCpu_IntrinsicsTasking.h"
/*********************************************************************************************************************/
/*------------------------------------------------------Macros-------------------------------------------------------*/
/*********************************************************************************************************************/
#define SPI_CLOCK                   4
#define MAX_ATOM_CHANNELS           5
#define  MOSI_CHANNELS              3
#define MASTER_TIMER_ISR            18
#define QUAD_SPI_DMA_ISR            16
#define ATOM_BITSHIFT               15
#define QUAD_SPI_BUFFER_SIZE        128
#define QUAD_SPI_MAXSIZE            256
#define QAUD_SPI_FILLLEVEL          64
#define MAX_FIFODATA                100
#define ATOM_CHANNELS               8

/*********************************************************************************************************************/
/*-------------------------------------------------Global variables--------------------------------------------------*/
/* Structure for three phase PWM output configuration and handling */
typedef struct
{
    IfxGtm_Atom_Timer    timer;                  /* Timer driver                                                      */
    IfxGtm_Atom_PwmHl    pwm;                    /* GTM TOM PWM driver object                                         */
    Ifx_TimerValue      pwmOnTimes[3];          /* PWM ON-time for 3 phases                                          */
    IfxGtm_Atom_Serial  update;
    uint32              spiPeriod;
} QSPIATOM_OUTPUT;

static QSPIATOM_OUTPUT QSpiAtom_Output;

volatile boolean QSpiAtom_SpiEnd = TRUE;
volatile boolean QSpiAtom_SpiReady = TRUE;

IfxDma_Dma_Channel QSpiAtom_DataChannel[MOSI_CHANNELS];

static QSPIATOM_SPIBUFFER QSpiAtom_TxBuffer[MOSI_CHANNELS] =
{
    NULL_PTR,
    NULL_PTR,
    NULL_PTR
};

static volatile QSPIATOM_MOSIREGS QSpiAtom_MosiChannels[MOSI_CHANNELS] =
{
    NULL_PTR,
    NULL_PTR,
    NULL_PTR
};

static volatile QSPIATOM_MOSIREGS QSpiAtom_SpiClk = NULL_PTR;

static volatile QSPIATOM_MOSIREGS QSpiAtom_ChipSelect = NULL_PTR;

static volatile QSPIATOM_MOSIREGS QSpiAtom_Timer = NULL_PTR;

static volatile uint32 QSpiAtom_DataRemain = 0;
/*********************************************************************************************************************/
/*--------------------------------------------Private Variables/Constants--------------------------------------------*/

/*********************************************************************************************************************/
/*********************************************************************************************************************/
/*------------------------------------------------Function Prototypes------------------------------------------------*/
/*********************************************************************************************************************/
IFX_STATIC void IfxGtmAtomSerialUpdate(IfxGtm_Atom_PwmHl *driver, Ifx_TimerValue *tOn);
/*********************************************************************************************************************/
/*---------------------------------------------Function Implementations----------------------------------------------*/
/*********************************************************************************************************************/
IFX_INTERRUPT(QSpiAtom_Isr,0, MASTER_TIMER_ISR);
void QSpiAtom_Isr(void)
{
    switch (QSpiAtom_DataRemain)
    {
      case 0:
      {
        QSpiAtom_DataChannel[0].dma->CH[QSpiAtom_DataChannel[0].channelId].CHCSR.B.SCH = 1;
        QSpiAtom_ChipSelect->SR1.U = 0xFFFF;
        QSpiAtom_SpiClk->SR1.U = 0x0000;
        QSpiAtom_DataRemain = 129;
        /* Prepare the SpiEnd to be TRUE */
        break;
      }

      case 129:
      {
        IfxGtm_Atom_Timer_stop(&QSpiAtom_Output.timer);
        QSpiAtom_SpiEnd = TRUE;
        break;
      }

      default:
      {
        QSpiAtom_DataChannel[0].dma->CH[QSpiAtom_DataChannel[0].channelId].CHCSR.B.SCH = 1;
        QSpiAtom_DataRemain--;
        break;
      }
    }
    QSpiAtom_Timer->IRQ_NOTIFY.U = 0x1;
}

/*This function sets default pwm signals for every phase*/
IFX_STATIC void IfxGtmAtomSerialUpdateOff(IfxGtm_Atom_PwmHl *driver, Ifx_TimerValue *tOn)
{
  uint8 ChannelIndex;

  for (ChannelIndex = 0; ChannelIndex < driver->base.channelCount; ChannelIndex++)
  {
    IfxGtm_Atom_Ch_setCompareOne(driver->atom, driver->ccxTemp[ChannelIndex],
        tOn[ChannelIndex]);
  }
}


IFX_STATIC void IfxGtmAtomSerialUpdatePeriod(IfxGtm_Atom_PwmHl *driver)
{
  uint8 ChannelIndex;
  for (ChannelIndex = 0; ChannelIndex < driver->base.channelCount; ChannelIndex++)
  {
    IfxGtm_Atom_Ch_setCompareZeroShadow(driver->atom, driver->ccxTemp[ChannelIndex],
        ATOM_BITSHIFT);
  }
}

/*This function runs the function pointer of the QSpiAtom_Output.update structure and sets the dutycycle of the pwm signals*/
void IfxGtm_AtomSerialThreeTimersSetOnTime(IfxGtm_Atom_PwmHl *driver, Ifx_TimerValue *tOn)
{
    QSpiAtom_Output.update.setMode(driver, tOn);
}


/*This function Starts the three phase pwm signals*/
IFX_STATIC void IfxGtmAtomSerialUpdate(IfxGtm_Atom_PwmHl *driver, Ifx_TimerValue *tOn)
{
  uint8          channelIndex;
  Ifx_TimerValue period;

  period = driver->timer->base.period;

  for (channelIndex = 1; channelIndex < driver->base.channelCount; channelIndex++)
  {
    IfxGtm_Atom_Ch_setCompareOneShadow(driver->atom, driver->ccxTemp[channelIndex],
        tOn[channelIndex] << 6);
  }
}

/*This pointer of structures has the different modes of the three phase signals, at first we use the configuration of
 * IfxGtmAtomSerialchModes[1] structure and then the configuration of IfxGtmAtomSerialchModes[0] structure*/
IFX_STATIC IFX_CONST IfxGtm_Atom_Serial IfxGtmAtomSerialchModes[2] = {
    {Ifx_Pwm_Mode_centerAligned,         FALSE, &IfxGtmAtomSerialUpdate  },
    {Ifx_Pwm_Mode_off,                   FALSE, &IfxGtmAtomSerialUpdateOff   }
    /*To add two more modes*/
};


IFX_STATIC void IfxGtmAtomStoreSrRegs(IfxGtm_Atom_PwmHl *driver)
{
  QSpiAtom_Timer = IfxGtm_Atom_Ch_getChannelPointer(QSpiAtom_Output.timer.atom, QSpiAtom_Output.timer.timerChannel);

  /* Get the Chip Select Register */
  QSpiAtom_ChipSelect = IfxGtm_Atom_Ch_getChannelPointer(driver->atom, driver->ccx[3]);

  QSpiAtom_SpiClk = IfxGtm_Atom_Ch_getChannelPointer(driver->atom, driver->ccx[4]);

  /* Get the Mosi Registers */
  for(uint8 channelIndex = 0; channelIndex < driver->base.channelCount-2; channelIndex++)
  {
    QSpiAtom_MosiChannels[channelIndex] = IfxGtm_Atom_Ch_getChannelPointer(driver->atom, driver->ccx[channelIndex]);
  }

}

/*This function sets the mode of the three phase pwm signals*/
boolean IfxGtm_AtomSerialThreeTimersSetMode(IfxGtm_Atom_PwmHl *driver, Ifx_Pwm_Mode mode)
{
    boolean                Result = TRUE;
    IfxGtm_Atom_PwmHl_Base *Base   = &driver->base;
    IfxGtm_Atom_Ch Channel;

    if (Base->mode != mode)
    {
        if (mode > Ifx_Pwm_Mode_off)
        {
            mode = Ifx_Pwm_Mode_off;
            Result = FALSE;
        }

        IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, mode == IfxGtm_Atom_Pwmccx_modes[mode].mode);

        Base->mode             = mode;
        QSpiAtom_Output.update         = IfxGtmAtomSerialchModes[0];

            driver->ccxTemp   = driver->ccx;

        {   /* Workaround to enable the signal inversion required for center aligned inverted
             * and right aligned modes */
            /** \note that changing signal level may produce short circuit at the power stage,
             * in which case the inverter must be disable during this action. */

            /* Ifx_Pwm_Mode_centerAligned and Ifx_Pwm_Mode_LeftAligned use inverted=FALSE */
            /* Ifx_Pwm_Mode_centerAlignedInverted and Ifx_Pwm_Mode_RightAligned use inverted=TRUE */
            uint32 ChannelIndex;

            for (ChannelIndex = 0; ChannelIndex < driver->base.channelCount; ChannelIndex++)
            {

                Channel = driver->ccx[ChannelIndex];
                IfxGtm_Atom_Ch_setSignalLevel(driver->atom, Channel, Base->ccxActiveState); /*Every phase must have the same signal level, active state high*/
            }
        }
    }

    return Result;
}



/*This function returns true when the three timers are initialized correctly*/
boolean IfxGtm_AtomSerialChannelsInit(IfxGtm_Atom_PwmHl *driver, IfxGtm_Atom_PwmHl_Config *config) {
    boolean           Result = TRUE;
    uint16            ChannelMask;
    uint16            ChannelsMask = 0;
    uint32            ChannelIndex;
    IfxGtm_Atom_Timer  *Timer        = config->timer;

    driver->base.mode             = Ifx_Pwm_Mode_init;
    driver->timer                 = Timer;
    driver->base.setMode          = 0;
    driver->base.inverted         = FALSE;
    driver->base.ccxActiveState   = config->base.ccxActiveState; /*Gets the active state of pwm signals from the configuration struct*/
    driver->base.channelCount     = config->base.channelCount; /*Gets the max channel count of controlled pwm signals by the master timer*/


    driver->atom = &(Timer->gtm->ATOM[config->atom]); /*Gets the Tom used as master*/

    /* config->ccx[0] is used for the definition of the TGC */
    driver->agc = (Ifx_GTM_ATOM_AGC *)&driver->atom->AGC.GLB_CTRL; /*In case we have channels from 0-6 we enable global control register 0*/


    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, config->base.channelCount <=MAX_ATOM_CHANNELS); /*In case we have less than 2 controlled pwm signals return 0*/

    IfxGtm_Cmu_Clk Clock = IfxGtm_Atom_Ch_getClockSource(Timer->atom, Timer->timerChannel); /*Set prescaler for every phase*/

    for (ChannelIndex = 0; ChannelIndex < config->base.channelCount; ChannelIndex++)
    {
        IfxGtm_Atom_Ch Channel;
        /* CCX */
        Channel                   = config->ccx[ChannelIndex]->channel;
        driver->ccx[ChannelIndex] = Channel;
        ChannelMask               = 1 << (Channel);
        ChannelsMask             |= ChannelMask;

        /* Initialize the timer part */
        IfxGtm_Atom_Ch_configureOutputSerial(driver->atom, Channel, Clock,
            driver->base.ccxActiveState, FALSE);

        /* Initialize the port */
        if ( (config->initPins == TRUE) )
        {
            IfxGtm_PinMap_setAtomTout(config->ccx[ChannelIndex],
                config->base.outputMode, config->base.outputDriver);
        }
    }
    IfxGtm_Atom_Agc_enableChannelsOutput(driver->agc, ChannelsMask, 0, TRUE);
    IfxGtm_Atom_Agc_enableChannels(driver->agc, ChannelsMask, 0, TRUE);


    IfxGtm_AtomSerialThreeTimersSetMode(driver, Ifx_Pwm_Mode_off); /*Enable the timers by having zero dutycycle*/

    Ifx_TimerValue tOn[MAX_ATOM_CHANNELS] = {0x0, 0x0, 0x0, 0xFFFF, 0x0};
    IfxGtmAtomSerialUpdateOff(driver, tOn);     /* tOn do not need defined values */
    /* Transfer the shadow registers */
    IfxGtm_Atom_Agc_setChannelsForceUpdate(driver->agc, ChannelsMask, 0, 0, 0);
    IfxGtm_Atom_Agc_trigger(driver->agc);
    IfxGtm_Atom_Agc_setChannelsForceUpdate(driver->agc, 0, ChannelsMask, 0, 0);

    /* Enable timer to update the channels */
    for (ChannelIndex = 0; ChannelIndex < driver->base.channelCount; ChannelIndex++)
    {
        IfxGtm_Atom_Timer_addToChannelMask(Timer, driver->ccx[ChannelIndex]);
    }

    IfxGtmAtomStoreSrRegs(driver);

    /* Here we set up the daisy chain dma channels */
    QSpiAtom_DataChannel[0].channelId = IfxDma_ChannelId_10;
    Dma_InitDaisyChainMaster(&QSpiAtom_DataChannel[0], 1, (uint32)(&QSpiAtom_TxBuffer[0][0]),
        (uint32)(&QSpiAtom_MosiChannels[0]->SR1.U), 0,IfxDma_ChannelIncrementCircular_512,
        IfxDma_ChannelIncrementCircular_none, IfxDma_ChannelMoveSize_16bit);

    QSpiAtom_DataChannel[1].channelId = IfxDma_ChannelId_9;
    Dma_InitDaisyChain(&QSpiAtom_DataChannel[1], 1, (uint32)(&QSpiAtom_TxBuffer[1][0]),
        (uint32)(&QSpiAtom_MosiChannels[1]->SR1.U), 0,IfxDma_ChannelIncrementCircular_512,
        IfxDma_ChannelIncrementCircular_none, IfxDma_ChannelMoveSize_16bit);

    QSpiAtom_DataChannel[2].channelId = IfxDma_ChannelId_8;
    Dma_InitDaisyChain(&QSpiAtom_DataChannel[2], 1, (uint32)(&QSpiAtom_TxBuffer[2][0]),
        (uint32)(&QSpiAtom_MosiChannels[2]->SR1.U), 0,IfxDma_ChannelIncrementCircular_512,
        IfxDma_ChannelIncrementCircular_none, IfxDma_ChannelMoveSize_16bit);

    return Result;
}

/*Main function of the Three timers Phase shift PWM*/
void QSpiAtom_Init(float32 baseFrequency,IfxGtm_Atom_ToutMap* masterPin, IfxGtm_Atom_ToutMapP* slavePins,
                          QSPIATOM_INPUTBUFFER* Message)
{
  QSpiAtom_TxBuffer[0] = Message[0];
  QSpiAtom_TxBuffer[1] = Message[1];
  QSpiAtom_TxBuffer[2] = Message[2];
  IfxGtm_Cmu_Clk ClckSrc= IfxGtm_Cmu_Clk_4;
  float32 frequency;
  /* Enable GTM, it is necessary if the GTM is not initialized earlier */
  
  IfxGtm_enable(&MODULE_GTM);

  frequency = IfxGtm_Cmu_getModuleFrequency(&MODULE_GTM);
  /* Set the global clock frequency to the max */
  IfxGtm_Cmu_setGclkFrequency(&MODULE_GTM, frequency);

  IfxGtm_Cmu_setClkFrequency(&MODULE_GTM, ClckSrc, baseFrequency);
  
  IfxGtm_Cmu_enableClocks(&MODULE_GTM, IFXGTM_CMU_CLKEN_CLK4);
  IfxGtm_Atom_Timer_Config TimerConfig;                                        /* Timer configuration              */
  IfxGtm_Atom_Timer_initConfig(&TimerConfig, &MODULE_GTM);                     /* Initialize timer configuration   */


  /*init pwm using the IfxGtm_Atom_Timer_Config of the Tom timer library*/
  TimerConfig.irqModeTrigger       = IfxGtm_IrqMode_pulseNotify;              /* Enable the pulse of the Output signal as interrupt*/
  TimerConfig.base.frequency       = baseFrequency;                           /* Set timer frequency */
  TimerConfig.base.isrPriority     = MASTER_TIMER_ISR;                        /* Enable the master timer ISR */
  TimerConfig.base.isrProvider     = IfxSrc_Tos_cpu0;                         /* Isr on cpu 0 */
  TimerConfig.atom                  = masterPin->atom;                          /* Define the timer used */
  TimerConfig.timerChannel         = masterPin->channel;                      /* Define the channel used */
  TimerConfig.clock                = ClckSrc;

  IfxGtm_Atom_TimerSerial_init(&QSpiAtom_Output.timer, &TimerConfig, ATOM_BITSHIFT , FALSE);   /* Initialize the TOM */
  IfxGtm_Atom_Agc_enableChannelUpdate(QSpiAtom_Output.timer.agc,QSpiAtom_Output.timer.triggerChannel,TRUE);

  /* Initialize the slave mosi channels */
  IfxGtm_Atom_PwmHl_Config PwmHlConfig;

  IfxGtm_Atom_ToutMapP Ccx[] =
          {
              slavePins[0], /* Mosi 1 */
              slavePins[1], /* Mosi 2 */
              slavePins[2], /* Mosi 3 */
              slavePins[3],  /* Chip select */
              slavePins[4]  /* Clock */
          };
  IfxGtm_Atom_PwmHl_initConfig(&PwmHlConfig);
  PwmHlConfig.base.channelCount = MAX_ATOM_CHANNELS; /* Controlled channels are three */

  PwmHlConfig.base.outputMode = IfxPort_OutputMode_pushPull; /* Output mode is push pull */


  PwmHlConfig.base.outputDriver = IfxPort_PadDriver_cmosAutomotiveSpeed1; /* Pad driver speed grade 1 */

  /* Set top PWM active state */
  PwmHlConfig.base.ccxActiveState = Ifx_ActiveState_low;


  PwmHlConfig.ccx   = Ccx;                        /* Assign the channels for High-side switches   */

  PwmHlConfig.timer = &QSpiAtom_Output.timer;  /* Use as master timer the timer we initialized */
  PwmHlConfig.atom   = TimerConfig.atom;


  IfxGtm_AtomSerialChannelsInit(&QSpiAtom_Output.pwm, &PwmHlConfig); /* Run the initialize of the three timers function */

  /* Set the shadow registers */
  IfxGtm_AtomSerialThreeTimersSetMode(&QSpiAtom_Output.pwm, Ifx_Pwm_Mode_centerAligned);

  /* Update the input frequency */
  IfxGtm_Atom_Timer_updateInputFrequency(&QSpiAtom_Output.timer);

  /* Initialize the cm0 registers with the bitshift */
  IfxGtm_Atom_Timer_disableUpdate(&QSpiAtom_Output.timer);
  IfxGtmAtomSerialUpdatePeriod(&QSpiAtom_Output.pwm);
  IfxGtm_Atom_Timer_applyUpdate(&QSpiAtom_Output.timer);  /* Start every PWM signal at the same time */
  QSpiAtom_SpiEnd = FALSE;
  /* Start the clocks in order to stop them at the same time inside the isr */
  QSpiAtom_ChipSelect->CN0.U = 0xF;
  QSpiAtom_SpiClk->CN0.U =0xF;
  QSpiAtom_Output.timer.atom->CH0.CN0.U = 0xF;
  IfxGtm_Atom_Timer_run(&QSpiAtom_Output.timer);

}


void QSpiAtom_StartQuadSpiTranscaction(uint32 size)
{
  if (QSpiAtom_SpiEnd == TRUE)
  {
    for (uint8 i = 0; i < MOSI_CHANNELS; i++)
    {
      QSpiAtom_MosiChannels[i]->CN0.U = 0xF;
      IfxDma_Dma_setChannelSourceAddress(&QSpiAtom_DataChannel[i], (uint32)(&QSpiAtom_TxBuffer[i][0]));
      /* Set the next data to be zero */
      QSpiAtom_TxBuffer[i][size] = 0;
    }
    /* Transfer with Dma to all the fifos */
    QSpiAtom_DataChannel[0].dma->CH[QSpiAtom_DataChannel[0].channelId].CHCSR.B.SCH = 1;
    /* Prepare the chip select */
    QSpiAtom_ChipSelect->SR1.U = 0x0000;
    /* Spi Clock */
    QSpiAtom_SpiClk->SR1.U = 0x5555;
    QSpiAtom_SpiEnd =  FALSE;

    QSpiAtom_Output.timer.atom->CH0.CN0.U = 0xF;
    QSpiAtom_ChipSelect->CN0.U = 0xF;
    QSpiAtom_SpiClk->CN0.U =0xF;
    QSpiAtom_DataRemain = size;
    
    QSpiAtom_DataRemain--;
    IfxGtm_Atom_Timer_run(&QSpiAtom_Output.timer);
  }
}
